config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index"
  resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) # 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = Item.order("expiration")
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if  @item.save
      redirect_to items_path
    else
      redirect_to action: "new"
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to items_path
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

end

private
  def item_params
    params.require(:item).permit(:name, :purchase, :stock, :expiration).merge(user_id: current_user.id)
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/index.html.haml
= render "items/header"
.main
  .main_box
    .main_box_name
      %p 【冷蔵庫管理アプリ】
    - if user_signed_in?
      = link_to items_path do
        .main_box_start
          %span.main_box_start_btn
            スタート
    - else 
      = link_to new_user_registration_path do
        .main_box_start
          %span.main_box_start_btn
            新規登録

app/views/items/_exisibition.html.haml
= link_to new_item_path do
  .exisibition
    %span.exisibition__text
      食品登録

app/views/items/_header.html.haml
%header.header
  .header_box
    %ul.header_box_right
    - if user_signed_in?
      %li.header_box_right_name
        = link_to "ログアウト", destroy_user_session_path, method: :delete
    - else
      %li.header_box_right_name
        = link_to "ログイン", new_user_session_path
      %li.header_box_right_name
        = link_to "新規登録", new_user_registration_path
    = link_to root_path do
      %p.header_box_center
        【冷蔵庫管理アプリ】

app/views/items/edit.html.haml
= render "header"
.new
  .new_box
    = form_with model: @item do |f|
      .new_box_titel
        登録食品編集
      .new_box_name
        .new_box_name_titel
          ・食品名
        .new_box_name_input
          = f.text_field :name, placeholder: "例) たまご"
      .new_box_purchase
        .new_box_purchase_titel
          ・購入日
        .new_box_purchase_input
          = f.text_field :purchase, placeholder: "例) 20200601"
      .new_box_stock
        .new_box_stock_titel
          ・個数
        .new_box_stock_input
          = f.number_field :stock,placeholder: "例) 10"
      .new_box_expiration
        .new_box_expiration_titel
          ・賞味期限
        .new_box_expiration_input
          = f.text_field :expiration, placeholder: "例) 20200606"
      .new_box_submit
        .new_box_submit_btn
          = f.submit '編集'
        .new_box_submit_root
          = link_to "食品一覧にもどる",items_path

app/views/items/index.html.haml
= render "items/header"
.product
  .product_box
    .product_box_titel
      = current_user.name
      さんの冷蔵庫一覧
    %span ※賞味期限の近い順
    .product_box_item
      .product_box_item_list
        .product_box_item_list_expiration
          賞味期限
        .product_box_item_list_name
          食品名
        .product_box_item_list_stock
          個数
        .product_box_item_list_purchase
          購入日
        .product_box_item_list_btn
          .product_box_item_list_btn_edit
            %span.edit_btn
              編集
          .product_box_item_list_btn_delete
            %span.edit_btn
              削除
      - @items.each do |item|
        - if user_signed_in? && current_user.id == item.user_id
          .product_box_item_list
            .product_box_item_list_expiration
              =item.expiration
            .product_box_item_list_name
              =item.name
            .product_box_item_list_stock
              =item.stock
            .product_box_item_list_purchase
              =item.purchase
            .product_box_item_list_btn
              = link_to edit_item_path(item) do
                .product_box_item_list_btn_edit
                  %span.edit_btn
                    編集
              = link_to item_path(item),method: :delete do
                .product_box_item_list_btn_delete
                  %span.delete_btn
                    削除
= render 'exisibition'
  

app/views/items/new.html.haml
= render "header"
.new
  .new_box
    = form_with model: @item do |f|
      .new_box_titel
        食品登録
      .new_box_name
        .new_box_name_titel
          ・食品名
        .new_box_name_input
          = f.text_field :name, placeholder: "例) たまご"
      .new_box_purchase
        .new_box_purchase_titel
          ・購入日
        .new_box_purchase_input
          = f.text_field :purchase, placeholder: "例) 20200601"
      .new_box_stock
        .new_box_stock_titel
          ・個数
        .new_box_stock_input
          = f.number_field :stock,placeholder: "例) 10"
      .new_box_expiration
        .new_box_expiration_titel
          ・賞味期限
        .new_box_expiration_input
          = f.text_field :expiration, placeholder: "例) 20200606"
      .new_box_submit
        .new_box_submit_btn
          = f.submit '登録'
        .new_box_submit_root
          = link_to "食品一覧にもどる",items_path

app/views/items/show.html.haml
= render "header"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title 在庫管理アプリ
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield